from typing import Literal

Margin = Literal[
    'm-auto',
    'm-px',
    '-m-px',
    'mx-auto',
    'mx-px',
    '-mx-px',
    'my-auto',
    'my-px',
    '-my-px',
    'ms-auto',
    'ms-px',
    '-ms-px',
    'me-auto',
    'me-px',
    '-me-px',
    'mt-auto',
    'mt-px',
    '-mt-px',
    'mr-auto',
    'mr-px',
    '-mr-px',
    'mb-auto',
    'mb-px',
    '-mb-px',
    'ml-auto',
    'ml-px',
    '-ml-px',
    'space-x-px',
    '-space-x-px',
    'space-y-px',
    '-space-y-px',
    'space-x-reverse',
    'space-y-reverse',
]
