from typing import Literal

MaxWidth = Literal[
    'max-w-3xs',
    'max-w-2xs',
    'max-w-xs',
    'max-w-sm',
    'max-w-md',
    'max-w-lg',
    'max-w-xl',
    'max-w-2xl',
    'max-w-3xl',
    'max-w-4xl',
    'max-w-5xl',
    'max-w-6xl',
    'max-w-7xl',
    'max-w-none',
    'max-w-px',
    'max-w-full',
    'max-w-dvw',
    'max-w-dvh',
    'max-w-lvw',
    'max-w-lvh',
    'max-w-svw',
    'max-w-svh',
    'max-w-screen',
    'max-w-min',
    'max-w-max',
    'max-w-fit',
    'container',
]
