
from typing import Literal

from nicegui.element import Element

BoxShadow = Literal[
    'shadow-sm',
    'shadow',
    'shadow-md',
    'shadow-lg',
    'shadow-xl',
    'shadow-2xl',
    'shadow-inner',
    'shadow-none'
]

BoxShadowColor = Literal[
    'shadow-inherit',
    'shadow-current',
    'shadow-transparent',
    'shadow-black',
    'shadow-white',
    'shadow-slate-50',
    'shadow-slate-100',
    'shadow-slate-200',
    'shadow-slate-300',
    'shadow-slate-400',
    'shadow-slate-500',
    'shadow-slate-600',
    'shadow-slate-700',
    'shadow-slate-800',
    'shadow-slate-900',
    'shadow-gray-50',
    'shadow-gray-100',
    'shadow-gray-200',
    'shadow-gray-300',
    'shadow-gray-400',
    'shadow-gray-500',
    'shadow-gray-600',
    'shadow-gray-700',
    'shadow-gray-800',
    'shadow-gray-900',
    'shadow-zinc-50',
    'shadow-zinc-100',
    'shadow-zinc-200',
    'shadow-zinc-300',
    'shadow-zinc-400',
    'shadow-zinc-500',
    'shadow-zinc-600',
    'shadow-zinc-700',
    'shadow-zinc-800',
    'shadow-zinc-900',
    'shadow-neutral-50',
    'shadow-neutral-100',
    'shadow-neutral-200',
    'shadow-neutral-300',
    'shadow-neutral-400',
    'shadow-neutral-500',
    'shadow-neutral-600',
    'shadow-neutral-700',
    'shadow-neutral-800',
    'shadow-neutral-900',
    'shadow-stone-50',
    'shadow-stone-100',
    'shadow-stone-200',
    'shadow-stone-300',
    'shadow-stone-400',
    'shadow-stone-500',
    'shadow-stone-600',
    'shadow-stone-700',
    'shadow-stone-800',
    'shadow-stone-900',
    'shadow-red-50',
    'shadow-red-100',
    'shadow-red-200',
    'shadow-red-300',
    'shadow-red-400',
    'shadow-red-500',
    'shadow-red-600',
    'shadow-red-700',
    'shadow-red-800',
    'shadow-red-900',
    'shadow-orange-50',
    'shadow-orange-100',
    'shadow-orange-200',
    'shadow-orange-300',
    'shadow-orange-400',
    'shadow-orange-500',
    'shadow-orange-600',
    'shadow-orange-700',
    'shadow-orange-800',
    'shadow-orange-900',
    'shadow-amber-50',
    'shadow-amber-100',
    'shadow-amber-200',
    'shadow-amber-300',
    'shadow-amber-400',
    'shadow-amber-500',
    'shadow-amber-600',
    'shadow-amber-700',
    'shadow-amber-800',
    'shadow-amber-900',
    'shadow-yellow-50',
    'shadow-yellow-100',
    'shadow-yellow-200',
    'shadow-yellow-300',
    'shadow-yellow-400',
    'shadow-yellow-500',
    'shadow-yellow-600',
    'shadow-yellow-700',
    'shadow-yellow-800',
    'shadow-yellow-900',
    'shadow-lime-50',
    'shadow-lime-100',
    'shadow-lime-200',
    'shadow-lime-300',
    'shadow-lime-400',
    'shadow-lime-500',
    'shadow-lime-600',
    'shadow-lime-700',
    'shadow-lime-800',
    'shadow-lime-900',
    'shadow-green-50',
    'shadow-green-100',
    'shadow-green-200',
    'shadow-green-300',
    'shadow-green-400',
    'shadow-green-500',
    'shadow-green-600',
    'shadow-green-700',
    'shadow-green-800',
    'shadow-green-900',
    'shadow-emerald-50',
    'shadow-emerald-100',
    'shadow-emerald-200',
    'shadow-emerald-300',
    'shadow-emerald-400',
    'shadow-emerald-500',
    'shadow-emerald-600',
    'shadow-emerald-700',
    'shadow-emerald-800',
    'shadow-emerald-900',
    'shadow-teal-50',
    'shadow-teal-100',
    'shadow-teal-200',
    'shadow-teal-300',
    'shadow-teal-400',
    'shadow-teal-500',
    'shadow-teal-600',
    'shadow-teal-700',
    'shadow-teal-800',
    'shadow-teal-900',
    'shadow-cyan-50',
    'shadow-cyan-100',
    'shadow-cyan-200',
    'shadow-cyan-300',
    'shadow-cyan-400',
    'shadow-cyan-500',
    'shadow-cyan-600',
    'shadow-cyan-700',
    'shadow-cyan-800',
    'shadow-cyan-900',
    'shadow-sky-50',
    'shadow-sky-100',
    'shadow-sky-200',
    'shadow-sky-300',
    'shadow-sky-400',
    'shadow-sky-500',
    'shadow-sky-600',
    'shadow-sky-700',
    'shadow-sky-800',
    'shadow-sky-900',
    'shadow-blue-50',
    'shadow-blue-100',
    'shadow-blue-200',
    'shadow-blue-300',
    'shadow-blue-400',
    'shadow-blue-500',
    'shadow-blue-600',
    'shadow-blue-700',
    'shadow-blue-800',
    'shadow-blue-900',
    'shadow-indigo-50',
    'shadow-indigo-100',
    'shadow-indigo-200',
    'shadow-indigo-300',
    'shadow-indigo-400',
    'shadow-indigo-500',
    'shadow-indigo-600',
    'shadow-indigo-700',
    'shadow-indigo-800',
    'shadow-indigo-900',
    'shadow-violet-50',
    'shadow-violet-100',
    'shadow-violet-200',
    'shadow-violet-300',
    'shadow-violet-400',
    'shadow-violet-500',
    'shadow-violet-600',
    'shadow-violet-700',
    'shadow-violet-800',
    'shadow-violet-900',
    'shadow-purple-50',
    'shadow-purple-100',
    'shadow-purple-200',
    'shadow-purple-300',
    'shadow-purple-400',
    'shadow-purple-500',
    'shadow-purple-600',
    'shadow-purple-700',
    'shadow-purple-800',
    'shadow-purple-900',
    'shadow-fuchsia-50',
    'shadow-fuchsia-100',
    'shadow-fuchsia-200',
    'shadow-fuchsia-300',
    'shadow-fuchsia-400',
    'shadow-fuchsia-500',
    'shadow-fuchsia-600',
    'shadow-fuchsia-700',
    'shadow-fuchsia-800',
    'shadow-fuchsia-900',
    'shadow-pink-50',
    'shadow-pink-100',
    'shadow-pink-200',
    'shadow-pink-300',
    'shadow-pink-400',
    'shadow-pink-500',
    'shadow-pink-600',
    'shadow-pink-700',
    'shadow-pink-800',
    'shadow-pink-900',
    'shadow-rose-50',
    'shadow-rose-100',
    'shadow-rose-200',
    'shadow-rose-300',
    'shadow-rose-400',
    'shadow-rose-500',
    'shadow-rose-600',
    'shadow-rose-700',
    'shadow-rose-800',
    'shadow-rose-900'
]

Opacity = Literal[
    'opacity-0',
    'opacity-5',
    'opacity-10',
    'opacity-20',
    'opacity-25',
    'opacity-30',
    'opacity-40',
    'opacity-50',
    'opacity-60',
    'opacity-70',
    'opacity-75',
    'opacity-80',
    'opacity-90',
    'opacity-95',
    'opacity-100'
]

MixBlendMode = Literal[
    'mix-blend-normal',
    'mix-blend-multiply',
    'mix-blend-screen',
    'mix-blend-overlay',
    'mix-blend-darken',
    'mix-blend-lighten',
    'mix-blend-color-dodge',
    'mix-blend-color-burn',
    'mix-blend-hard-light',
    'mix-blend-soft-light',
    'mix-blend-difference',
    'mix-blend-exclusion',
    'mix-blend-hue',
    'mix-blend-saturation',
    'mix-blend-color',
    'mix-blend-luminosity',
    'mix-blend-plus-lighter'
]

BackgroundBlendMode = Literal[
    'bg-blend-normal',
    'bg-blend-multiply',
    'bg-blend-screen',
    'bg-blend-overlay',
    'bg-blend-darken',
    'bg-blend-lighten',
    'bg-blend-color-dodge',
    'bg-blend-color-burn',
    'bg-blend-hard-light',
    'bg-blend-soft-light',
    'bg-blend-difference',
    'bg-blend-exclusion',
    'bg-blend-hue',
    'bg-blend-saturation',
    'bg-blend-color',
    'bg-blend-luminosity'
]


class Effects:

    def __init__(self, element: Element = Element('')) -> None:
        self.element = element

    def __add(self, _class: str) -> None:
        self.element.classes(add=_class)

    def apply(self, ex_element: Element) -> Element:
        """Apply the Style to an outer element.

        :param ex_element: External Element
        :return: External Element
        """
        return ex_element.classes(add=' '.join(self.element._classes))

    def box_shadow(self, _box_shadow: BoxShadow):
        """Utilities for controlling the box shadow of an element."""
        self.__add(_box_shadow)
        return self

    def box_shadow_color(self, _box_shadow_color: BoxShadowColor):
        """Utilities for controlling the color of a box shadow."""
        self.__add(_box_shadow_color)
        return self

    def opacity(self, _opacity: Opacity):
        """Utilities for controlling the opacity of an element."""
        self.__add(_opacity)
        return self

    def mix_blend_mode(self, _mix_blend_mode: MixBlendMode):
        """Utilities for controlling how an element should blend with the background."""
        self.__add(_mix_blend_mode)
        return self

    def background_blend_mode(self, _background_blend_mode: BackgroundBlendMode):
        """Utilities for controlling how an element's background image should blend with its background color."""
        self.__add(_background_blend_mode)
        return self
