from . import (
    badge_documentation,
    button_documentation,
    button_dropdown_documentation,
    button_group_documentation,
    checkbox_documentation,
    codemirror_documentation,
    chip_documentation,
    color_input_documentation,
    color_picker_documentation,
    date_documentation,
    doc,
    input_documentation,
    joystick_documentation,
    knob_documentation,
    number_documentation,
    radio_documentation,
    range_documentation,
    select_documentation,
    slider_documentation,
    switch_documentation,
    teleport_documentation,
    textarea_documentation,
    time_documentation,
    toggle_documentation,
    upload_documentation,
)

doc.title('*Controls*')

doc.intro(button_documentation)
doc.intro(button_group_documentation)
doc.intro(button_dropdown_documentation)
doc.intro(badge_documentation)
doc.intro(chip_documentation)
doc.intro(toggle_documentation)
doc.intro(radio_documentation)
doc.intro(select_documentation)
doc.intro(checkbox_documentation)
doc.intro(switch_documentation)
doc.intro(slider_documentation)
doc.intro(range_documentation)
doc.intro(joystick_documentation)
doc.intro(input_documentation)
doc.intro(textarea_documentation)
doc.intro(codemirror_documentation)
doc.intro(number_documentation)
doc.intro(knob_documentation)
doc.intro(color_input_documentation)
doc.intro(color_picker_documentation)
doc.intro(date_documentation)
doc.intro(time_documentation)
doc.intro(upload_documentation)
doc.intro(teleport_documentation)
