start = "align-self: flex-start;"
end = "align-self: flex-end;"
center = "align-self: center;"
baseline = "lign-self: baseline;"
stretch = "align-self: stretch;"
space_around = "align-self: space-around;"

justify_start = "justify-content: flex-start;"
justify_end = "justify-content: flex-end;"
justify_center = "justify-content: center;"
justify_between = "justify-content: space-between;"
justify_around = "justify-content: space-around;"
justify_evenly = "justify-content: space-evenly;"

items_start = "align-items: flex-start;"
items_end = "align-items: flex-end;"
items_center = "align-items: center;"
items_baseline = "align-items: baseline;"
items_stretch = "align-items: stretch;"

content_start = "align-content: flex-start;"
content_end = "align-content: flex-end;"
content_center = "align-content: center;"
content_stretch = "align-content: stretch;"
content_between = "align-content: space-between;"
content_around = "align-content: space-around;"
